CRONAPP-2431 Falha ao consumir webservice na IDE em relação ao Postman
technecloud/cronapi-java pull request #140
Opened 2020-09-24 13:47 UTC by tiagoromano

2020-09-28 20:53 UTC, disantana commented on src/main/java/cronapi/util/Operations.java
> +    if (methodAsString.equalsIgnoreCase(HttpPost.METHOD_NAME)) {
Para evitar nullpointer, é interessante inverter a condição para `HttpPost.METHOD_NAME.equalsIgnoreCase(methodAsString)`, exemplo.

2020-09-28 20:58 UTC, disantana commented on src/main/java/cronapi/HttpDeleteWithBody.java
> +      throw new RuntimeException(e);
É interessante usar o log para exibirmos o erro no console antes de lançar a exceção.

2020-09-28 20:59 UTC, disantana commented on src/main/java/cronapi/HttpGetWithBody.java
> +      throw new RuntimeException(e);
É interessante usar o log para exibirmos o erro no console antes de lançar a exceção.

2020-09-28 21:23 UTC, disantana requested changes
Se faz necessário realizar alguns ajustes para melhorar a rastreabilidade de erros e também, evitar NPE futuros.

2020-09-29 15:00 UTC, tiagoromano commented on src/main/java/cronapi/util/Operations.java
> +    if (methodAsString.equalsIgnoreCase(HttpPost.METHOD_NAME)) {
Boa

2020-09-29 15:02 UTC, tiagoromano commented on src/main/java/cronapi/HttpDeleteWithBody.java
> +      throw new RuntimeException(e);
Nesse caso, eu prefiro levantar mesmo o Exception, porque o usuário não consegue perceber o que ocorre, levantando uma exceção ele visualiza mais rápido, coloquei para logar, mas mantive a exceção

2020-09-29 16:14 UTC, disantana approved these changes

2020-09-29 16:15 UTC, merged